# Generated by Django 4.2 on 2025-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_for',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='alllog',
            old_name='unique_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='alllog',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alllog',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
