# Generated by Django 4.2 on 2025-12-01 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='timing',
            new_name='end_timing',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='start_timing',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
