# Generated by Django 4.2 on 2025-12-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_timing_doctorprofile_end_timing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluser',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
