# Generated by Django 4.2 on 2025-11-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_doctor_created_by_remove_doctor_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllLog',
            new_name='AllUser',
        ),
    ]
