# Generated by Django 4.2 on 2025-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_alllog_alluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='user_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
