# Generated by Django 4.2 on 2025-11-24 21:59

from django.db import migrations, models
import django.db.models.deletion
import queue


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_department_patientprofile_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(default=queue.Full, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
